server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 修正属性名（原配置为driver，此处为正确写法）
    url: jdbc:mysql://192.168.128.142:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true  # 添加允许公钥检索
    username: root
    password: 123
  redis:
    host: 192.168.128.142
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug